"""empty message

Revision ID: 660a109a1261
Revises: 
Create Date: 2023-01-31 18:45:23.758713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660a109a1261'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('skill_name', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('porcentage', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
